Traceback (most recent call last):
  File "/home/wf/d/coolS/pudb2022/pudb/__init__.py", line 158, in runscript
    dbg._runscript(mainpyfile)
  File "/home/wf/d/coolS/pudb2022/pudb/debugger.py", line 507, in _runscript
    self.run(statement)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/bdb.py", line 580, in run
    exec(cmd, globals, locals)
  File "<string>", line 1, in <module>
  File "train_timm.py", line 1018, in <module>
  File "train_timm.py", line 754, in main
    loader_eval                 ,
  File "train_timm.py", line 1005, in validate
  File "/home/wf/d/s_kaggle/working/ap_score.py", line 324, in export_ap_score
    score = event_detection_ap(solution[solution['video_id'].isin(infer_df['video_id'].unique())],
  File "/home/wf/d/s_kaggle/working/ap_score.py", line 237, in event_detection_ap
    solution
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 961, in __getitem__
    return self._getitem_tuple(key)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1140, in _getitem_tuple
    return self._getitem_lowerdim(tup)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 843, in _getitem_lowerdim
    return self._getitem_nested_tuple(tup)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 942, in _getitem_nested_tuple
    obj = getattr(obj, self.name)._getitem_axis(key, axis=axis)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1194, in _getitem_axis
    return self._getitem_iterable(key, axis=axis)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1132, in _getitem_iterable
    keyarr, indexer = self._get_listlike_indexer(key, axis)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexing.py", line 1330, in _get_listlike_indexer
    keyarr, indexer = ax._get_indexer_strict(key, axis_name)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5796, in _get_indexer_strict
    self._raise_if_missing(keyarr, indexer, axis_name)
  File "/home/wf/anaconda3/envs/t_pool3/lib/python3.9/site-packages/pandas/core/indexes/base.py", line 5856, in _raise_if_missing
    raise KeyError(f"None of [{key}] are in the [{axis_name}]")
KeyError: "None of [Index(['start', 'end'], dtype='object', name='event')] are in the [columns]"
